export const toolFaqs = {
  'merge-pdf': [
    { q: 'Is there a limit on how many PDFs I can merge?', a: 'No. You can merge as many PDF files as you need in one go, with no file size limit per file (up to 100 MB each).' },
    { q: 'Can I merge PDFs on my phone?', a: 'Yes. Breklo works on any modern browser including Safari on iPhone and Chrome on Android. No app download needed.' },
    { q: 'Will merging PDFs reduce quality?', a: 'No. Merging only combines the existing pages — it does not re-render or recompress any content. The quality of each page is preserved exactly.' },
    { q: 'Can I merge password-protected PDFs?', a: 'Password-protected PDFs need to be unlocked before merging. Remove the password first, then merge.' },
    { q: 'How do I merge PDFs in a specific order?', a: 'Use the up and down arrows next to each file in the Breklo merge tool to arrange them in the correct order before clicking Merge.' },
    { q: 'Is my data safe when merging PDFs online?', a: 'Yes. Breklo processes everything in your browser. Your files are never uploaded to any server.' },
  ],
  'split-pdf': [
    { q: 'How do I split a PDF into individual pages?', a: 'Use the Split all pages mode. Each page of your PDF becomes a separate PDF file that downloads automatically.' },
    { q: 'Can I extract specific pages from a PDF?', a: 'Yes. Use the Extract page range mode and enter the pages you want, for example 2,4,6-10.' },
    { q: 'Is there a page limit for splitting?', a: 'No. You can split PDFs of any length. There is no page limit.' },
    { q: 'Will splitting affect the quality of the PDF?', a: 'No. Splitting only separates pages — it does not re-render or recompress any content. Quality is preserved exactly.' },
    { q: 'Can I split a password-protected PDF?', a: 'Password-protected PDFs need to be unlocked before splitting.' },
    { q: 'How do I split a PDF on my phone?', a: 'Breklo works on any mobile browser. Open the Split PDF tool in Safari or Chrome on your phone, upload the PDF from your files app, and download the result.' },
  ],
  'compress-pdf': [
    { q: 'Does compressing a PDF reduce image quality?', a: 'It depends on the mode. Basic compression is lossless — no quality change. Medium and High modes re-render pages as images, which reduces quality slightly in exchange for much smaller file sizes.' },
    { q: 'How much can I reduce a PDF file size?', a: 'Typical results range from 20% reduction (Basic, text-only PDFs) to 80% reduction (High mode, scanned or image-heavy PDFs).' },
    { q: 'Is there a file size limit?', a: 'Breklo supports PDFs up to 100 MB. All processing happens in your browser, so there are no server-side limits.' },
    { q: 'Will the compressed PDF look different?', a: 'In Basic mode, the PDF is visually identical. In Medium and High modes, text-based pages may show slight softening, but for screen reading it is generally unnoticeable.' },
    { q: 'Can I compress a scanned PDF?', a: 'Yes. High compression mode is specifically effective for scanned PDFs, as it re-renders each page at a lower DPI.' },
    { q: 'Is my PDF uploaded to a server?', a: 'No. All processing happens entirely in your browser using WebAssembly. Your file never leaves your device.' },
  ],
  'rotate-pdf': [
    { q: 'Can I rotate only some pages in a PDF?', a: 'The current tool rotates all pages at once. To rotate individual pages, use the Organize PDF tool which gives per-page control.' },
    { q: 'What rotation angles are available?', a: 'You can rotate by 90°, 180° or 270°. These cover all standard orientation corrections.' },
    { q: 'Will rotating a PDF affect the text?', a: 'No. Rotating is a non-destructive operation — the text, images and formatting are preserved exactly.' },
    { q: 'Can I rotate a scanned PDF?', a: 'Yes. Scanned PDFs are just images embedded in a PDF, and rotating works the same way.' },
    { q: 'Is there a file size limit for rotating?', a: 'Up to 100 MB. All processing happens in your browser.' },
    { q: 'How do I rotate a PDF on my phone?', a: 'Open the Rotate PDF tool in your mobile browser, upload from your files app, choose the angle, and download the rotated PDF.' },
  ],
  'organize-pdf': [
    { q: 'Can I reorder individual pages within a PDF?', a: 'Yes. The Organize PDF tool loads all pages and lets you move each one up or down using the arrow controls.' },
    { q: 'Is there a limit on how many pages I can reorder?', a: 'No. You can reorder PDFs of any length. For very large documents, the page list is scrollable.' },
    { q: 'Will reordering affect PDF quality?', a: 'No. Reordering is non-destructive — pages are copied in the new order without any re-rendering.' },
    { q: 'Can I delete pages while organizing?', a: 'The Organize tool is focused on reordering. To delete pages, use the Delete PDF Pages tool first, then organize the remaining pages.' },
    { q: 'Does the tool show page previews?', a: 'Currently the tool shows page numbers. Visual thumbnails are coming in a future update.' },
    { q: 'Is my PDF safe when using this tool?', a: 'Yes. All processing happens in your browser. Your file is never uploaded to any server.' },
  ],
  'extract-pdf-pages': [
    { q: 'How do I extract a single page from a PDF?', a: 'Enter just the page number in the pages field. For example, entering "3" extracts only page 3 as a new PDF.' },
    { q: 'Can I extract non-consecutive pages?', a: 'Yes. Use commas to separate pages: "1,4,7" extracts pages 1, 4 and 7. Use dashes for ranges: "1-5" extracts pages 1 through 5.' },
    { q: 'What is the difference between Split PDF and Extract PDF Pages?', a: 'Split PDF can create a separate file for every page. Extract PDF Pages lets you specify exactly which pages you want and saves them into one new document.' },
    { q: 'Will the extracted pages keep their original formatting?', a: 'Yes. Pages are copied directly without any re-rendering. All text, images and formatting are preserved.' },
    { q: 'Is there a limit on how many pages I can extract?', a: 'No. You can extract any number of pages from a PDF of any length.' },
    { q: 'Can I extract pages from a scanned PDF?', a: 'Yes. The tool works with all PDF types including scanned documents.' },
  ],
  'delete-pdf-pages': [
    { q: 'How do I delete a single page from a PDF?', a: 'Enter the page number in the pages field. For example, "3" deletes only page 3. The result is a new PDF with all other pages intact.' },
    { q: 'Can I delete multiple pages at once?', a: 'Yes. Enter comma-separated pages or ranges: "2,4,6-8" deletes pages 2, 4, 6, 7 and 8.' },
    { q: 'Is the original PDF modified?', a: 'No. A new PDF is created and downloaded. Your original file is never modified.' },
    { q: 'Can I delete all pages?', a: 'No. The tool prevents you from deleting all pages since the result would be an empty PDF.' },
    { q: 'Will deleting pages affect the remaining content?', a: 'No. The remaining pages are preserved exactly — no re-rendering or quality loss.' },
    { q: 'Is there a page limit?', a: 'No. The tool works with PDFs of any length.' },
  ],
  'password-protect-pdf': [
    { q: 'How strong is the PDF password protection?', a: 'Breklo uses 128-bit AES encryption, which is the standard for PDF security and sufficient for most use cases.' },
    { q: 'Can I remove the password later?', a: 'Yes. Use a PDF password remover tool with the correct password to unlock the protected PDF.' },
    { q: 'What restrictions does the password add?', a: 'The password prevents opening the document. It also disables copying and editing while allowing printing. You can adjust these in the advanced options.' },
    { q: 'Is the minimum password length enforced?', a: 'Yes. A minimum of 4 characters is required. We recommend using a longer password with a mix of letters, numbers and symbols.' },
    { q: 'Is my PDF uploaded to a server when adding a password?', a: 'No. All encryption happens in your browser. Your file and password never leave your device.' },
    { q: 'Can I password-protect a PDF on my phone?', a: 'Yes. The tool works on any mobile browser. Open it in Safari or Chrome, upload your PDF, set the password, and download.' },
  ],
  'pdf-to-jpg': [
    { q: 'Does the PDF to JPG converter work on all PDFs?', a: 'Yes, including text PDFs, scanned PDFs, and image-heavy PDFs. Each page is rendered as a high-resolution JPG regardless of content.' },
    { q: 'What resolution are the output JPG files?', a: 'Pages are rendered at 2x scale, producing images around 1700×2200 pixels for an A4 page — suitable for printing and high-quality sharing.' },
    { q: 'Can I convert just one page of a PDF to JPG?', a: 'First use the Extract PDF Pages tool to pull out that page, then convert the single-page PDF to JPG.' },
    { q: 'How many pages can I convert at once?', a: 'There is no limit. Each page becomes a separate JPG file that downloads automatically.' },
    { q: 'Will text be sharp in the JPG output?', a: 'Yes. The 2x render scale ensures text remains crisp and readable in the output images.' },
    { q: 'Is PDF to JPG conversion free on Breklo?', a: 'Yes, completely free with no page limits and no signup required.' },
  ],
  'pdf-to-png': [
    { q: 'What is the difference between PDF to JPG and PDF to PNG?', a: 'PNG is a lossless format that supports transparency. JPG is smaller but lossy. For PDFs with sharp graphics or transparent elements, PNG is better. For photos and presentations, JPG is fine.' },
    { q: 'What resolution are the output PNG files?', a: 'Pages are rendered at 2x scale for high-resolution output, typically around 1700×2200 pixels for an A4 page.' },
    { q: 'Are PNG files larger than JPG files?', a: 'Yes. PNG is lossless, so file sizes are larger than equivalent JPGs. If file size matters more than exact quality, use PDF to JPG instead.' },
    { q: 'Can I convert a scanned PDF to PNG?', a: 'Yes. Scanned PDFs are rendered page by page into PNG images just like regular PDFs.' },
    { q: 'Is there a page limit for PDF to PNG conversion?', a: 'No. All pages are converted. Each page becomes a separate PNG file.' },
    { q: 'Is the conversion free?', a: 'Yes, completely free with no limits and no signup required.' },
  ],
  'pdf-to-text': [
    { q: 'Does PDF to text work on scanned PDFs?', a: 'Scanned PDFs are images, not text, so the tool cannot extract text from them directly. Only PDFs with real embedded text (created digitally) work with this tool. For scanned PDFs, OCR is needed (coming soon).' },
    { q: 'Is the extracted text editable?', a: 'Yes. You can copy the text from the preview box and paste it anywhere, or download it as a .txt file for editing in any text editor.' },
    { q: 'Will the formatting be preserved?', a: 'Basic structure is preserved (paragraphs, line breaks) but complex formatting like tables, columns and special layouts may not convert perfectly.' },
    { q: 'How many pages can I extract text from?', a: 'There is no page limit. All pages are processed and separated with page markers in the output.' },
    { q: 'Can I download the extracted text?', a: 'Yes. Click the Download .txt button to save the extracted text as a plain text file.' },
    { q: 'Is my PDF content safe?', a: 'Yes. All processing happens in your browser. Your PDF content never reaches any server.' },
  ],
  'jpg-to-pdf': [
    { q: 'Can I convert multiple JPG files to one PDF?', a: 'Yes. Add as many JPG files as you need. They will all be combined into a single PDF, one image per page, in the order you arrange them.' },
    { q: 'What size will the PDF pages be?', a: 'Each page matches the dimensions of the original image. A landscape photo becomes a landscape page; a portrait photo becomes a portrait page.' },
    { q: 'Can I combine JPG and PNG files into one PDF?', a: 'For mixed formats, use the Image to PDF tool, which accepts JPG, PNG, WebP and GIF all at once.' },
    { q: 'Will the image quality be preserved in the PDF?', a: 'Yes. The images are embedded directly into the PDF without re-compression. Quality is preserved exactly.' },
    { q: 'How do I make the pages A4 size?', a: 'Use the Image to PDF tool, which has an option to fit images to A4 pages rather than using the original image dimensions.' },
    { q: 'Can I convert a JPG to PDF on my phone?', a: 'Yes. Breklo works in any mobile browser. Open the tool, upload from your photos app, and download the PDF.' },
  ],
  'png-to-pdf': [
    { q: 'Does PNG to PDF preserve transparency?', a: 'PDF does not support transparency natively. Transparent areas in the PNG will be filled with a white background in the output PDF.' },
    { q: 'Can I combine multiple PNG files into one PDF?', a: 'Yes. Add multiple PNG files and they will each become a page in one combined PDF document.' },
    { q: 'Will the PNG quality be preserved in the PDF?', a: 'Yes. Images are embedded directly without re-compression or quality loss.' },
    { q: 'What if I have a mix of PNG and JPG files?', a: 'Use the Image to PDF tool, which accepts PNG, JPG, WebP and GIF together.' },
    { q: 'Is there a file size limit?', a: 'Up to 100 MB per file. All processing happens in your browser.' },
    { q: 'Can I reorder images before converting to PDF?', a: 'Yes. Use the up and down arrows next to each file to arrange them before converting.' },
  ],
  'image-to-pdf': [
    { q: 'What image formats does Image to PDF support?', a: 'JPG, PNG, WebP and GIF are all supported. You can mix different formats in one conversion.' },
    { q: 'What is the difference between Original size and A4 mode?', a: 'Original size creates PDF pages that match the exact dimensions of each image. A4 mode fits each image onto a standard A4 page with white margins.' },
    { q: 'Can I combine different image types into one PDF?', a: 'Yes. Mix JPG, PNG, WebP and GIF files freely — each becomes a page in the combined PDF.' },
    { q: 'Will the image quality be preserved?', a: 'Yes for original mode. Images are embedded as-is without re-compression.' },
    { q: 'Does GIF animation get preserved in the PDF?', a: 'No. Only the first frame of an animated GIF is used as the PDF page.' },
    { q: 'Is there a limit on how many images I can convert?', a: 'No. Add as many images as you need and they will all be combined into one PDF.' },
  ],
  'compress-image': [
    { q: 'What image formats can I compress on Breklo?', a: 'JPG, PNG, WebP and GIF are all supported. All formats output as JPG after compression for maximum size reduction.' },
    { q: 'What is the difference between the compression presets?', a: 'Web (70% quality) is ideal for websites. Email (60%) produces smaller files for attachments. Maximum (45%) gives the smallest possible file. Custom lets you set exact quality and maximum dimensions.' },
    { q: 'Does compressing an image reduce its dimensions?', a: 'Yes, if the image exceeds the maximum pixel size for the preset. Web preset limits images to 1200px on the longest side.' },
    { q: 'Can I compress multiple images at once?', a: 'Yes. Drop as many images as you need onto the upload area and they all compress together.' },
    { q: 'What is WebP and should I use it for web images?', a: 'WebP is a modern image format that is 25–35% smaller than JPG or PNG at the same quality. All modern browsers support it.' },
    { q: 'Will compressed images look different on a website?', a: 'At 70% quality, the difference from the original is generally invisible at screen resolution.' },
  ],
  'heic-to-jpg': [
    { q: 'Why can\'t I open HEIC files on Windows?', a: 'Windows does not support HEIC natively. You either need to install the HEIF Image Extensions from the Microsoft Store, or convert the file to JPG first using Breklo.' },
    { q: 'Does converting HEIC to JPG reduce quality?', a: 'There is a small quality reduction since JPG uses lossy compression. At 90% quality the difference is invisible in normal viewing.' },
    { q: 'Can I convert multiple HEIC files at once?', a: 'Yes. Drop multiple HEIC files onto the upload area and they all convert in one go.' },
    { q: 'What is the difference between HEIC and HEIF?', a: 'HEIF is the container format standard, and HEIC is Apple\'s implementation of it. They are effectively the same thing.' },
    { q: 'Is HEIC conversion free on Breklo?', a: 'Yes, completely free with no file limits and no signup required.' },
    { q: 'Will the converted JPG have the same dimensions as the original?', a: 'Yes. The image dimensions are preserved exactly. Only the format and file size change.' },
  ],
  'jpg-to-png': [
    { q: 'Why would I convert JPG to PNG?', a: 'PNG is a lossless format that supports transparency. Convert to PNG when you need to edit an image without further quality loss, or when you need a transparent background.' },
    { q: 'Will converting JPG to PNG improve quality?', a: 'No. The quality of the original JPG is preserved but not improved. PNG prevents further quality loss in future edits.' },
    { q: 'Are PNG files larger than JPG files?', a: 'Yes. PNG is lossless so files are typically 3–5x larger than equivalent JPGs. Use PNG when quality matters more than file size.' },
    { q: 'Can I convert multiple JPG files at once?', a: 'Yes. Drop multiple JPG files onto the upload area and they all convert together.' },
    { q: 'Is there a quality loss when converting JPG to PNG?', a: 'No. The conversion is lossless — the PNG output is a pixel-perfect copy of the JPG input.' },
    { q: 'Is the conversion free?', a: 'Yes, completely free with no limits and no signup required.' },
  ],
  'png-to-jpg': [
    { q: 'Why would I convert PNG to JPG?', a: 'JPG files are significantly smaller than PNGs, making them better for sharing, emailing and web use. Convert to JPG when file size matters more than lossless quality.' },
    { q: 'What happens to transparent areas when converting PNG to JPG?', a: 'Transparent areas are filled with a white background, since JPG does not support transparency.' },
    { q: 'How much smaller will the JPG be compared to the PNG?', a: 'Typically 3–5x smaller at 90% quality, and up to 10x smaller at lower quality settings.' },
    { q: 'Can I convert multiple PNG files at once?', a: 'Yes. Drop multiple PNG files and they all convert together.' },
    { q: 'What quality setting should I use?', a: '90% is a good default — virtually indistinguishable from the original but significantly smaller. Use 70–80% for web images where size matters most.' },
    { q: 'Is the conversion free?', a: 'Yes, completely free with no limits and no signup required.' },
  ],
  'jpg-to-webp': [
    { q: 'What is WebP and why should I use it?', a: 'WebP is a modern image format by Google. It produces files 25–35% smaller than JPG at the same visual quality. All modern browsers support it, making it ideal for web use.' },
    { q: 'Is WebP supported by all browsers?', a: 'Yes. Chrome, Firefox, Safari (since 2020), Edge and all modern mobile browsers support WebP.' },
    { q: 'How much smaller will the WebP file be?', a: 'Typically 25–35% smaller than the equivalent JPG at the same quality level.' },
    { q: 'Can I convert multiple JPG files to WebP at once?', a: 'Yes. Drop multiple files and they all convert together.' },
    { q: 'Will text in images stay sharp after WebP conversion?', a: 'Yes. WebP handles sharp edges and text well at high quality settings.' },
    { q: 'Is the conversion free?', a: 'Yes, completely free with no limits and no signup required.' },
  ],
  'png-to-webp': [
    { q: 'Does PNG to WebP preserve transparency?', a: 'Yes. Unlike JPG, WebP supports transparency. Transparent areas in your PNG will be preserved in the WebP output.' },
    { q: 'How much smaller will the WebP file be compared to PNG?', a: 'Typically 50–80% smaller. WebP is much more efficient than PNG for web use.' },
    { q: 'Should I use WebP or JPG for my website?', a: 'WebP is the better choice. It is smaller than both JPG and PNG and supports transparency. All modern browsers support it.' },
    { q: 'Can I convert multiple PNG files to WebP at once?', a: 'Yes. Drop multiple PNG files and they all convert together.' },
    { q: 'Does WebP support animation?', a: 'Yes, but this converter outputs static WebP images only, not animated ones.' },
    { q: 'Is the conversion free?', a: 'Yes, completely free with no limits and no signup required.' },
  ],
  'merge-images': [
    { q: 'What image formats can I merge?', a: 'JPG, PNG, WebP and GIF are all supported. You can mix different formats in one merge operation.' },
    { q: 'Can I choose whether images are stacked vertically or horizontally?', a: 'Yes. Choose Vertical to stack images top to bottom, or Horizontal to place them side by side.' },
    { q: 'Can I add a gap between images?', a: 'Yes. Use the gap slider to add spacing between images in pixels. The gap is filled with the background color you choose.' },
    { q: 'What output formats are available?', a: 'You can output the merged image as JPG, PNG or WebP.' },
    { q: 'Is there a limit on how many images I can merge?', a: 'No. You can merge as many images as needed, though very large or many high-resolution images may take longer to process.' },
    { q: 'Can I reorder images before merging?', a: 'Yes. Use the up and down arrows to arrange images in the correct order before merging.' },
  ],
  'mp4-to-mp3': [
    { q: 'Does MP4 to MP3 conversion work on any video file?', a: 'It works on any video format your browser can decode, including MP4, MOV, WebM, MKV and AVI in most modern browsers.' },
    { q: 'How long does conversion take?', a: 'A typical 100 MB MP4 takes 10–30 seconds depending on your device. The browser decodes the audio track and re-encodes it as MP3 locally.' },
    { q: 'What bitrate should I choose?', a: '128kbps is standard for general use. Use 192kbps or 320kbps for music or high-quality audio. Use 96kbps for voice recordings and podcasts.' },
    { q: 'Can I extract audio from a YouTube video?', a: 'Breklo only works with files you upload from your device. You would need to download the video file first.' },
    { q: 'Will the audio quality match the original video?', a: 'The output quality is limited by the source audio. If the original MP4 had high-quality audio, choosing 192kbps or 320kbps will preserve it well.' },
    { q: 'Is there a file size limit?', a: 'Breklo supports files up to 100 MB. For larger files, processing may be slower depending on your device.' },
  ],
  'wav-to-mp3': [
    { q: 'Why convert WAV to MP3?', a: 'WAV files are uncompressed and very large. A 3-minute WAV file can be 30–50 MB, while the same audio as MP3 at 192kbps is only 4–5 MB — a 90% size reduction.' },
    { q: 'What bitrate should I use for WAV to MP3 conversion?', a: '192kbps is recommended when converting from WAV source material, as it preserves more of the original quality. 128kbps is fine for voice recordings.' },
    { q: 'Will the MP3 sound the same as the WAV?', a: 'At 192kbps or 320kbps, the difference is inaudible to most listeners. MP3 uses perceptual audio compression to remove frequencies humans cannot easily hear.' },
    { q: 'Is there a file size limit?', a: 'Up to 100 MB. WAV files are large, so a 100 MB WAV is about 10 minutes of stereo audio at 44.1kHz.' },
    { q: 'How long does WAV to MP3 conversion take?', a: 'Processing happens in your browser. A 50 MB WAV file typically converts in 15–30 seconds.' },
    { q: 'Is my audio file safe?', a: 'Yes. All processing happens in your browser. Your audio file never leaves your device.' },
  ],
  'mp3-to-wav': [
    { q: 'Why would I convert MP3 to WAV?', a: 'WAV is an uncompressed format required by many professional audio editors (Audacity, Adobe Audition, Logic Pro). Convert to WAV when you need to edit audio without further quality loss.' },
    { q: 'Will converting MP3 to WAV improve audio quality?', a: 'No. WAV is lossless but the quality of an MP3 cannot be recovered. The WAV file will be larger but will not sound better than the source MP3.' },
    { q: 'How much larger will the WAV file be?', a: 'Significantly larger. A 5 MB MP3 typically becomes 40–50 MB as WAV. Make sure you have enough storage space.' },
    { q: 'What sample rate and bit depth does the WAV output use?', a: 'The output uses 16-bit PCM at the original sample rate of the MP3 (typically 44.1kHz or 48kHz).' },
    { q: 'Is there a file size limit?', a: 'Input MP3 files up to 100 MB are supported. Note the output WAV will be much larger.' },
    { q: 'Is my audio file safe?', a: 'Yes. All processing happens in your browser. Your file never leaves your device.' },
  ],
};
